name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      env:
        REACT_APP_MY_SECRET: ${{ secrets.GROQ_API_KEY }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
